<a href="https://colab.research.google.com/github/ravi-prakash1907/Predictive-Analytics/blob/tuts/Python%20Basics/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Basics of NumPy
1. Intro  
2. NumPy vs List  
3. Operations on NumPy Array  
4. Mathematical & Statistical  Funstions

In [119]:
## loading library
import numpy as np

### Intro
_Creating a numpy array_

In [2]:
## creating array
a = np.array([1,2,3])
print(a)

[1 2 3]


In [3]:
a = np.array([(1,2,3),(4,5,6)])
print(a)

[[1 2 3]
 [4 5 6]]


### NumPy vs List
NumPy is prefered over the Lists, because:  
1. Occupies less memory  
2. Fast  
3. Convenient to work with NumPy arr

**validating...**

In [4]:
## loading lib
import time
import sys

##### **Memory comparision**

In [11]:
L1 = range(1000)  # 0-999
print("Size of list = ",len(L1))
print("Size of any single element in array = ",sys.getsizeof(L1[0]))
print("Space occupied our list is {}".format(sys.getsizeof(5)*len(L1)))

Size of list =  1000
Size of any single element in array =  24
Space occupied by '5' in our list is 28000


In [10]:
Arr1 = np.arange(1000)
print("Size of array = ",Arr1.size)
print("Size of any single element in array = ",Arr1.itemsize)
print("Space occupied by our np.array is {}".format(Arr1.size*Arr1.itemsize))

Size of array =  1000
Size of any single element in array =  8
Space occupied by our np.array is 8000


---

##### **Speed comparision**

In [18]:
Size = 100000

## adding 2 lists/arrays
L1 = range(Size)
L2 = range(Size)

A1 = np.arange(Size)
A2 = np.arange(Size)

In [19]:
start = time.time()
result = [(x,y) for x,y in zip(L1,L2)]
print("Time taken to add lists is {} sec.".format((time.time()-start)*1000))

Time taken to add lists is 42.598724365234375 sec.


In [20]:
start = time.time()
## convenient too
result = A1+A2
print("Time taken to add arrays is {} sec.".format((time.time()-start)*1000))

Time taken to add arrays is 12.630462646484375 sec.


### Operations on NumPy Array

#### Basics
1. finding dimention  
2. getting bytesize  
3. finding  data-types

In [21]:
arr = np.array([[1,2,3],[2,3,4]])
arr

array([[1, 2, 3],
       [2, 3, 4]])

In [25]:
## Dimention
print("Dimention is: ",arr.ndim)
## finding byte size
print("Space occupied by each element (in bytes): ",arr.itemsize)

Dimention is:  2
Space occupied by each element (in bytes):  8


In [27]:
arr = np.arange(4)

## Dimention
print("Dimention of {} is: {}".format(arr,arr.ndim))

Dimention of [0 1 2 3] is: 1


In [29]:
## datatype
arr.dtype

dtype('int64')

#### Additional operations
1. Size and Shape  
2. Reshaping  
3. Slicing

In [59]:
arr = np.arange(24)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [60]:
# size i.e. total elements
print("Size = ",arr.size)

# size total elements in each dim (i.e. in rows and cols)
print("Shape = ",arr.shape)

Size =  24
Shape =  (24,)


In [61]:
print("Element at index 5: ",arr[4])

Element at index 5:  4


In [62]:
arr = arr.reshape(8,3)
arr

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17],
       [18, 19, 20],
       [21, 22, 23]])

In [63]:
# size i.e. total elements
print("Size = ",arr.size)

# size total elements in each dim (i.e. in rows and cols)
print("Shape = ",arr.shape)

Size =  24
Shape =  (8, 3)


In [64]:
print("Element in row 3 and col 2: ",arr[2,1])

Element in row 3 and col 2:  7


In [67]:
arr = arr.reshape(3,2,4)
arr

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]],

       [[16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [68]:
# size i.e. total elements
print("Size = ",arr.size)

# size total elements in each dim (i.e. in rows and cols)
print("Shape = ",arr.shape)

Size =  24
Shape =  (3, 2, 4)


In [70]:
print("Element in row 2 and col 4 from 2nd last matrix: ",arr[-2, 1, 3])

Element in row 2 and col 4 from 2nd last matrix:  15


In [71]:
## print middle 2 values of first row every martix
arr[:,0,1:3]

array([[ 1,  2],
       [ 9, 10],
       [17, 18]])

#### Some inbuilt functions
1. linspace  
2. min  
3. max  
4. sum

In [77]:
# to find n number of values between 2 numbers 
## having equal gap
arr = np.linspace(0,10,5)
arr

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [78]:
arr = np.arange(12)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [84]:
## min
print("Min val = {} \nMax val = {} \nSum of elements = {}".format(arr.min(),
                                                                  arr.max(),
                                                                  arr.sum()))

Min val = 0 
Max val = 11 
Sum of elements = 66


#### Axis in NumPy
1. Columns = axis 0  
2. Rows = axis 1  

In [88]:
arr = np.arange(1,31).reshape(6,5)
print(arr)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]
 [26 27 28 29 30]]


In [95]:
print("Shape: ",arr.shape)

## finding row sum
rowSum = arr.sum(axis=1)
## finding col sum
colSum = arr.sum(axis=0)

Shape:  (6, 5)


In [96]:
print("Sum of all rows:",rowSum)
print("Total elements in sum array: ",len(rowSum))

Sum of all rows: [ 15  40  65  90 115 140]
Total elements in sum array:  6


In [97]:
print("Sum of all columns:",colSum)
print("Total elements in sum array: ",len(colSum))

Sum of all columns: [ 81  87  93  99 105]
Total elements in sum array:  5


### Math Operations

In [98]:
arr = np.arange(5)
arr

array([0, 1, 2, 3, 4])

In [99]:
## addition
arr+2

array([2, 3, 4, 5, 6])

In [100]:
## multiplication
arr*3

array([ 0,  3,  6,  9, 12])

In [101]:
## squareroot 
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ])

**element-wise operation between 2 np.arrays**

In [114]:
arr1 = np.arange(1,5).reshape(2,2)
arr2 = np.arange(5,9).reshape(2,2)

print("arr1: \n{} \n\narr2: \n{}".format(arr1,arr2))

arr1: 
[[1 2]
 [3 4]] 

arr2: 
[[5 6]
 [7 8]]


In [115]:
## Add
arr1 + arr2

array([[ 6,  8],
       [10, 12]])

In [116]:
## sub
arr1 - arr2

array([[-4, -4],
       [-4, -4]])

In [118]:
## div
arr2 // arr1

array([[5, 3],
       [2, 2]])

### Statistical Fun

In [103]:
print("Array: ",arr)

Array:  [0 1 2 3 4]


In [104]:
# mean
arr.mean()

2.0

In [105]:
# variance
arr.var()

2.0

In [106]:
# standard deviation
arr.std()

1.4142135623730951